name: MDVGraves
version: 1.0.4
main: xyz.mdvcraft.mdvgraves.MDVGravesPlugin
api-version: '1.21'
author: MDVCRAFT
description: Bolsas de muerte persistentes y ligeras para MDVCRAFT.
softdepend: [MMOItems, MythicLib, WorldGuard, ProtectionStones]
commands:
  mdvgraves:
    description: Administración de MDVGraves.
    usage: /mdvgraves <reload|cleanup|info|deleteall confirm>
    permission: mdvgraves.admin
permissions:
  mdvgraves.admin:
    default: op
  mdvgraves.texture.vip:
    default: false
  mdvgraves.texture.admin:
    default: op
